blank_issues_enabled: false
contact_links:
  - name: Azure AI Foundry Documentation
    url: https://learn.microsoft.com/en-us/azure/ai-foundry/
    about: Check the documentation for an overview, how-to-guides, and much more
