name: Feature Request
description: Suggest an idea for this project, like further examples or improvements
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new example, feature, or improvement!
  
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see.
      placeholder: Tell us about the feature...
    validations:
      required: true
      
  - type: textarea
    id: problem
    attributes:
      label: How This Feature Benefits
      description: Describe what this feature would address.
      placeholder: This feature would help with...
    validations:
      required: true
      
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low (nice to have)
        - Medium (would improve experience)
        - High (significantly improves learning or reflects latest AI Foundry service features and versions)
    validations:
      required: true
      
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request here.
